### ISSUE TITLE
Failed to connect to server from .net client

### ISSUE THREAD

**Issue by mobdk** [skelsec/pypykatz_agent_dn#1]
Hi
Running pypyserver on Ubuntu, no firewall running, server part is listning on port 8080, when try to run the .net agent on windows endpoint, I get the error displayed on the screen dump.

Please advice. Thanks

C:\Users\toor\Desktop\pypykatz_agent_dn\pypyagent\bin\Debug>pypyagent.exe 10.0.2.15 8080 
Trying to connect to server
Failed to connect to server! Reason: System.Net.Sockets.SocketException (0x80004005): No connection could be made because the target machine actively refused it 10.0.2.15:8080
   at System.Net.Sockets.TcpClient..ctor(String hostname, Int32 port)
   at pypyagent.PYPYReverseSocketTransport.connect() in C:\Users\victim\Desktop\pypykatz_agent_dn\pypyagent\transport.cs:line 21
   at pypyagent.PYPYagent.run() in C:\Users\victim\Desktop\pypykatz_agent_dn\pypyagent\agent.cs:line 24

Unhandled Exception: System.NullReferenceException: Object reference not set to an instance of an object.
   at pypyagent.PYPYReverseSocketTransport.readCMD() in C:\Users\victim\Desktop\pypykatz_agent_dn\pypyagent\transport.cs:line 32
   at pypyagent.PYPYagent.run() in C:\Users\victim\Desktop\pypykatz_agent_dn\pypyagent\agent.cs:line 35
   at pypyagent.Program.Main(String[] args) in C:\Users\victim\Desktop\pypykatz_agent_dn\pypyagent\Program.cs:line 33

C:\Users\toor\Desktop\pypykatz_agent_dn\pypyagent\bin\Debug>

**Comment by mobdk** [comment]
![Screenshot from 2019-03-27 11-38-41](https://user-images.githubusercontent.com/32879789/55070264-2f3edf00-5086-11e9-825f-cb5b1893a7ad.png)

**Comment by TacticalCheerio** [comment]
Have the same issue. Server is running on Kali with no firewalls, agent on Windows 10 both with default parameters. Verified I can connect/ssh into the Kali box from my Windows machine, but get the following error:

`pypyagent.exe 10.x.x.x 54545
Trying to connect to server
Failed to connect to server! Reason: System.Net.Sockets.SocketException (0x80004005): A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond 10.x.x.x:54545
   at System.Net.Sockets.TcpClient..ctor(String hostname, Int32 port)
   at pypyagent.PYPYReverseSocketTransport.connect()
   at pypyagent.PYPYagent.run()

Unhandled Exception: System.NullReferenceException: Object reference not set to an instance of an object.
   at pypyagent.PYPYReverseSocketTransport.readCMD()
   at pypyagent.PYPYagent.run()
   at pypyagent.Program.Main(String[] args)`

Tried running it as user and admin for both the pypyagent and pypyagent_35 executables.

**Comment by TacticalCheerio** [comment]
Changed the parameters from the default to:

Server: python server.py socket -l 0.0.0.0 -p 8888
Agent: pypyagent.exe 10.x.x.x 8888

And it works, weird. Works as well with pypyagent_35.exe

Too bad AV still caught it :)

**Comment by skelsec** [comment]
thanks for letting me know that it works now.
I'll close the ticket because:
1. I cannot reproduce it
2. Somehow I get the feeling it is related much more to networking issues on user side rather than programming issue.

AV flags it? meh...
